//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.22 at 02:02:51 下午 CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://wadl.dev.java.net/2009/02",
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
        xmlns={
        @javax.xml.bind.annotation.XmlNs(prefix="xsd",namespaceURI="http://www.w3.org/2001/XMLSchema"),
        @javax.xml.bind.annotation.XmlNs(prefix="tns",namespaceURI="urn:weibo:wn"),
        @javax.xml.bind.annotation.XmlNs(prefix="wn",namespaceURI="urn:weibo:wn"),
        @javax.xml.bind.annotation.XmlNs(prefix="wa",namespaceURI="urn:weibo:api")
},attributeFormDefault=javax.xml.bind.annotation.XmlNsForm.UNQUALIFIED)
package com.weibo.api.spec.wadl.wadl20090202;
